# Generated by Django 2.2.5 on 2020-07-06 06:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('levels', models.IntegerField(blank=True, null=True, verbose_name='Levels')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, geography=True, help_text='Geometry of the building', null=True, srid=4326, verbose_name='Geometry')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Price')),
                ('kind', models.CharField(choices=[('wood', 'Wood'), ('steel', 'Steel'), ('oil', 'Oil')], max_length=32, verbose_name='Kind')),
                ('pickup_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Where to get cargo', null=True, srid=4326, verbose_name='Pickup Point')),
                ('dropoff_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Where to delivery cargo', null=True, srid=4326, verbose_name='Dropoff Point')),
            ],
            options={
                'verbose_name': 'Delivery Job',
                'verbose_name_plural': 'Delivery Jobs',
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('waypoint', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Waypoint to pass', null=True, srid=4326, verbose_name='Waypoint')),
            ],
            options={
                'verbose_name': 'Waypoint',
                'verbose_name_plural': 'Waypoints',
            },
        ),
    ]
